on: [push]

jobs:
  build_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: rm -rf .git
      - uses: php-actions/composer@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: ./
          remote_path: CHANGE_PATH_HERE
          remote_host: CHANGE_HOST_HERE
          remote_user: root
          remote_key: ${{ secrets.SSH_KEY }}
