on: [push]

jobs:
  build_job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/install-composer
      - uses: ./.github/actions/install-node
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./

  deploy_job:
    name: Deploy
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: build
      - uses: ./.github/actions/deploy
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
